### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [104]:
import numpy as np
a=np.arange(0,10,1) # от 0 до 10 не включая, с шагом 1
a[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [105]:
# Еще один вариант
data=np.diag(range(10), k=0)
sum(data)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [106]:
data=np.diag(range(10), k=0) # k-коэф смещения диагонали

In [107]:
data.sum()

45

### Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [108]:
import pandas as pd
import numpy as np

In [109]:
movies_data=pd.read_csv('movies.csv')
movies_data.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [111]:
raitings_data=pd.read_csv('ratings.csv')
raitings_data.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [113]:
# Фильтруем данные по рейтингу с оценкой = 5.0
df=raitings_data.query('rating == "5.0"')
df.head()

userId  movieId  rating  timestamp
3       1       47     5.0  964983815
4       1       50     5.0  964982931
6       1      101     5.0  964980868
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [114]:
# находим id с наибольшим кол-вом оценок 5.  idxmax()=list(dict(best_movie).keys())[0] 
best_movieid=df['movieId'].value_counts().idxmax()
# извлекаем необходимую строчку с наименованием фильма
movies_data.loc[(movies_data['movieId'] == best_movieid)]


movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama

### Задание 4
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [115]:
import pandas as pd

In [116]:
df=pd.read_csv('power.csv')
df.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [117]:
df_filtred=df.loc[((df['country']=='Lithuania') | (df['country']=='Latvia') | (df['country']=='Estonia'))  # Прибалтика
           & ((df['quantity']>=0))    # только не отрицательные знчения
           & ((df['category']==4) | (df['category']==12) | (df['category']==21))   # для категорий 4,12,21
           & ((df['year']>=2005))     # от 2005г
           & ((df['year']<=2010))     # до 2010г
          ] 
df_filtred.shape

(408, 4)

 Проверка. Получим уникальные значения из столбцов отфильрованной таблицы.
 
 1.header=None помогает обратиться к заголовку таблицы
 
 2.df_for_check.head(1) - заголовок
 
 3.Цикл по кол-ву столбцов - len(list(df_for_check.head(1)))
 
 4.list(df_for_check.head(1)[i])[0] - наименование столбцов

 5.df_filtred[list(df_for_check.head(1)[i])[0]].unique()) - обращаюсь к каждому столбцу отфильтрованной таблицы для получения уникальных значений в каждом столбце.

In [118]:

df_for_check=pd.read_csv('power.csv', header=None)
df_for_check.head(1)
for i in range(len(list(df_for_check.head(1)))):
    print(list(df_for_check.head(1)[i])[0],sorted(df_filtred[list(df_for_check.head(1)[i])[0]].unique()))    

country ['Estonia', 'Latvia', 'Lithuania']
year [2005, 2006, 2007, 2008, 2009, 2010]
quantity [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 13.0, 16.0, 17.0, 18.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 34.0, 36.0, 47.0, 49.0, 50.0, 53.0, 54.0, 55.0, 57.0, 61.0, 62.0, 63.0, 74.0, 76.0, 77.0, 79.0, 90.0, 98.0, 103.0, 104.0, 107.0, 108.0, 109.0, 113.0, 121.0, 133.0, 139.0, 141.0, 142.0, 144.0, 151.0, 156.0, 161.0, 165.0, 188.0, 191.0, 195.0, 198.0, 199.0, 204.0, 213.0, 216.0, 220.0, 223.0, 286.0, 292.0, 351.0, 361.0, 369.0, 378.0, 558.0, 562.0, 571.0, 575.0, 576.0, 588.0, 591.0, 603.0, 760.0, 875.0, 876.0, 877.0, 937.0, 951.0, 953.0, 967.0, 1183.0, 1530.0, 1531.0, 1536.0, 1541.0, 1576.0, 1581.0, 2115.0, 2119.0, 2132.0, 2133.0, 2151.0, 2155.0, 2166.0, 2292.0, 2330.0, 2433.0, 2435.0, 2471.0, 2483.0, 2492.0, 2495.0, 2502.0, 2518.0, 2521.0, 2523.0, 2526.0, 2527.0, 2530.0, 2532.0, 2536.0, 2537.0, 2544.0, 2554.0, 2557.0, 2559.0, 2572.0, 2580.0, 2584.0, 259

C:\Users\89517_000\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (1,2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [119]:
# Пример
list(df_for_check.head(1)[1])[0]

'year'

In [120]:
# Пример
df_filtred[list(df_for_check.head(1)[1])[0]].unique()

array([2008, 2007, 2006, 2005, 2010, 2009], dtype=int64)

In [121]:
# Суммарное потребление стран
df_filtred['quantity'].sum()

240580.0

### Задание 5
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3


In [122]:
import numpy as np

In [123]:
A = np.array([
    [4,2,1],
    [1,3,0],
    [0,5,4]
])

B = np.array([
    [4],
    [12],
    [-3]
])
B

array([[ 4],
       [12],
       [-3]])

In [124]:
from scipy import linalg
x, y, z = linalg.solve(A,B)
print('x=',x, 'y=',y, 'z=',z)

x= [0.46666667] y= [3.84444444] z= [-5.55555556]
