In [1]:
import pandas as pd
import numpy as np
from datetime import datetime 

1.1 Дан произвольный список, содержащий только числа.Выведите результат сложения всех чисел больше 10.

In [30]:
a=np.arange(0,20)
a[4]

4

In [32]:
l=0
for i in range(len(a)):
       if a[i]>10:
            l=l+a[i]
print(l)

135


1.2 Пусть задан список, содержащий строки.Выведите все строки, заканчивающиеся буквой r.

In [45]:
spisok=['str', 'stra', 'stu', 'sttdr']

In [46]:
for i in spisok:
    if i[-1] == 'r':
        print(i)

str
sttdr


1.3 Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащую только цифры. Строка должна содержать хотя бы одну цифру 3. 

In [63]:
np.random.rand(6)+3

array([3.94584625, 3.20555824, 3.51138715, 3.49083411, 3.4624996 ,
       3.71649991])

1.4 Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов.

In [68]:
stroka='Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов'

In [69]:
# сколько символов
len(stroka)

102

In [71]:
# сколько слов
len(stroka.split(' '))

16

2.1 Пусть дана матрица чисел размером NхN. Представьте данную матрицу в виде списка. Выведите результат сложения всех элементов матрицы.

In [75]:
matrix=np.random.random((2,2))
matrix

array([[0.64172178, 0.80664488],
       [0.29241228, 0.33449969]])

In [76]:
matrix.sum()

2.0752786199553444

2.2 Дана матрица размером NxM. Напишите алгоритм вычисления максимума из сумм элементов каждого столбца. 

In [77]:
matrix2=np.random.random((2,3))
matrix2

array([[0.65411431, 0.42217778, 0.71245273],
       [0.51825888, 0.44095781, 0.95550465]])

In [79]:
matrix2.max()

0.9555046500737369

In [83]:
matrix2[0:2,1]

array([0.42217778, 0.44095781])

In [98]:
l=[]
for i in range(len(matrix2[0])):
    l.append(sum(matrix2[0:2,i]))
    print(i,'сумма столбца',sum(matrix2[0:2,i]).max())
print(sorted(l)[-1])


0 сумма столбца 1.1723731846491265
1 сумма столбца 0.8631355840699969
2 сумма столбца 1.6679573848200855
1.6679573848200855


3.1 Пусть список студентов представлен в виде структуры [[No, ФИО, Возраст,Группа],[No, ФИО, Возраст, Группа],[No, ФИО, Возраст, Группа]]. Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]} 

In [3]:
a=[['No1', 'ФИО1', 'Возраст1','Группа1'],['No2', 'ФИО2', 'Возраст2', 'Группа2'],['No3', 'ФИО3', 'Возраст3', 'Группа3']]
dictionary = {x[0]: x[1:] for x in a}
print(dictionary)



{'No1': ['ФИО1', 'Возраст1', 'Группа1'], 'No2': ['ФИО2', 'Возраст2', 'Группа2'], 'No3': ['ФИО3', 'Возраст3', 'Группа3']}


3.2 Напишите алгоритм, позволяющий найти запись в словаре из задачи 3.1 (без преобразования словаря обратно в список) по фамилии и изменить в ней номер группы. Фамилию и новый номер группы необходимо ввести с клавиатуры.

In [4]:
#def fam_group():
    

In [8]:
# через input() неудобно несколько раз прогонять, поэтому использовал просто значения a и b
a='ФИО2'
b='Группа3'
for key, value in dictionary.items():
    if a in value:
        value[2]=b
        print(key,value)
dictionary

No2 ['ФИО2', 'Возраст3', 'Группа3']


{'No1': ['ФИО1', 'Возраст1', 'Группа1'],
 'No2': ['ФИО2', 'Возраст3', 'Группа3'],
 'No3': ['ФИО3', 'Возраст3', 'Группа3']}

3.3 Напишите алгоритм, позволяющий аналогично задаче 3.2 изменить возраст студента

In [9]:
a='ФИО2'
b='Возраст3'
for key, value in dictionary.items():
    if a in value:
        value[1]=b
        print(key,value)
dictionary

No2 ['ФИО2', 'Возраст3', 'Группа3']


{'No1': ['ФИО1', 'Возраст1', 'Группа1'],
 'No2': ['ФИО2', 'Возраст3', 'Группа3'],
 'No3': ['ФИО3', 'Возраст3', 'Группа3']}